# .github/FUNDING.yml

# These are the supported funding-model platforms.
# For built-in ones you could add keys like: github, patreon, open_collective, ko_fi, etc.
# Since Cash App isn’t built-in, we’ll use a custom link:

custom:
  - name: "Cash App"
    url: "https://cash.app/$BubblesTheDev"

